server:
  port: 8081

logging:
  level:
    root: warn
    com.rest.api: debug

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name:
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate:
      hbm2ddl.auto: update
      format_sql: true
    showSql: true
    generate-ddl: true
  redis:
    cluster:
      nodes:
        - 15.164.98.87:6300
        - 15.164.98.87:6301
        - 15.164.98.87:6302
        - 15.164.98.87:6400
        - 15.164.98.87:6401
        - 15.164.98.87:6402
      max-redirects: 3
    password: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
